### ISSUE TITLE
Multiple RSS feeds and Mastodon accounts

### ISSUE THREAD

**Issue by jeroenpraat** [thomasb22/feedMastodon#2]
What is the best way to use different RSS feeds with different Mastodon accounts?

**Comment by thomasb22** [comment]
You can use the script in different directories. For exemple:

  * ~/website1/feedMastodon.py
  * ~/website2/feedMastodon.py
  * ~/website3/feedMastodon.py

**Comment by jeroenpraat** [comment]
Yes that was I did, but maybe I overlooked a parameter. Thanks.
