### ISSUE TITLE
Feature request: summary

### ISSUE THREAD

**Issue by jeroenpraat** [thomasb22/feedMastodon#3]
Is it possible that the script can extract the first 200 characters (+ a [...] if cut off) from the summary, and add it to the toot?

Like this:

> Title of article
> 
> "Summary article, etc, etc, etc, et [...]"
>
> https://linktosite/article

And the code would something like this:

`toot = title + '\n\n "' + summary + '" \n\n' + link`

**Comment by jeroenpraat** [comment]
I have done this in my code and for me it works. So maybe you can use this. It only has to add something for feeds without item.summary and maybe you want to have the summary a bit shorter to have space for hashtags (I don't use those for my feeds). I also do a * around the title for clarity.

```
        summary = (item.summary[:198] + '…') if len(item.summary) > 199 else item.summary
        toot = '*' + title + '*\n\n"' + summary + '"\n\n' + link
```

**Comment by jeroenpraat** [comment]
Eventually I had to take care of HTML summaries also (that I have to convert to text). I used Beautifulsoup for that (pip3 install beautifulsoup) with parser Lxml  (pip3 install lxml).

```python
from bs4 import BeautifulSoup
```
and
```python
        soup = BeautifulSoup(item.summary, 'lxml')
        summary = (soup.text[:199] + '…') if len(soup.text) > 200 else soup.text
        toot = '*' + title + '*\n\n"' + summary + '"\n\n' + link
```

Only thing missing now is what to do if there is no item.summary or an empty one. Or else we have double "'s.

But maybe you don't want this at all. So this is now a feature request with code suggestions ;-)

**Comment by thomasb22** [comment]
Thank you for this good suggestion. I have added this option, as well as the possibility to choose the maximum size of the messages ^^

**Comment by jeroenpraat** [comment]
Thanks! Do I understand correctly that it calculates the total of the used characters?

Two things:

1. I used BeautifulSoup cause that also converts HTML entities (like &quot;) to plain text. I don't think the Lxml is needed, the native Python html.parser will probably works as well).

2. I see you use […] from my first example. After some research I found out that a … (without the brackets) is more common to cut off a quote.

**Comment by jeroenpraat** [comment]
Closing now, but please see my previous comment.

**Comment by thomasb22** [comment]
Yes, it calculates the total of the used characters.
I didn't want to use BeautifulSoup because I wanted to avoid using a library outside to remove HTML tags.
But I hadn't thought of the HTML characters, thus to use BeautifulSoup was actually inevitable ^^

Thanks for your contribution ;-)

**Comment by jeroenpraat** [comment]
Now it works super great!

One thing left: I found out that titles sometimes also contains HTML entities, so title also needs BeautifulSoup:

```python
soup = BeautifulSoup(item.title, 'lxml')
title = soup.text
soup = BeautifulSoup(item.summary, 'lxml')
summary = soup.text
```

**Comment by thomasb22** [comment]
The worst it's because I had thought of it, but I forgot to apply it for the title…

Thank you for being also attentive ^^'
